/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kalkulatorwydatkow.gui;

import kalkulatorwydatkow.businesslogic.Autoryzacja;
import kalkulatorwydatkow.businesslogic.Kwota;
import kalkulatorwydatkow.businesslogic.Przypomnienia;
import kalkulatorwydatkow.businesslogic.Wydatki;
import kalkulatorwydatkow.model.Dokument;
import kalkulatorwydatkow.model.Prognoza;
import kalkulatorwydatkow.model.Przypomnienie;
import kalkulatorwydatkow.model.Sys;
import kalkulatorwydatkow.service.DokumentService;

import javax.swing.*;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import java.util.stream.Collectors;


public class Desktop extends javax.swing.JFrame {

    private Logowanie logowanie;

    private static final int kwotaGotowka = 1;
    private static final int kwotaKonta = 2;
    private static final int kwotaWszystko = 3;

    private int kwotaTryb = kwotaGotowka;

    private static final int wydatkiZwykle = 1;
    private static final int wydatkiStale = 2;
    private static final int wydatkiWszystkie = 3;

    private int wydatkiTryb = wydatkiZwykle;

    /**
     * Creates new form Desktop
     *
     * @param logowanie
     */
    public Desktop(Logowanie logowanie) {
        this.logowanie = logowanie;
        initComponents();

        init();
    }

    private void init() {
        if (Sys.zalogowany != null) {
            txtZalogowanyJako.setText(Sys.zalogowany.getImie() + " " +
                    Sys.zalogowany.getNazwisko() + " (" + Sys.zalogowany.getLogin() + ")");
        }

        aktualizujUzytkownikow();

        kwotaTryb = kwotaWszystko;
        aktualizujKwoty();

        wydatkiTryb = wydatkiWszystkie;
        aktualizujWydatki();

        aktualizujPrzypomnienia();
    }

    private void aktualizujUzytkownikow() {
        lstUzytkownicy.setListData(Autoryzacja.pobierzNazwyUzytkownikow().toArray(new String[0]));
    }

    private void aktualizujPrzypomnienia() {
        ArrayList<Przypomnienie> nowePrzypomnienia = new ArrayList<>();

        // wydatki stałe
        Calendar cal = Calendar.getInstance();
        int currentDayOfMonth = cal.get(Calendar.DAY_OF_MONTH);

        Wydatki.pobierzStaleObj().forEach(w -> {
            Calendar cal2 = Calendar.getInstance();
            cal2.setTime(w.getData());
            int dayOfMonthWydatekStaly = cal2.get(Calendar.DAY_OF_MONTH);

            SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
            String formatted = format.format(cal.getTime());

            if (currentDayOfMonth == dayOfMonthWydatekStaly) {
                nowePrzypomnienia.add(new Przypomnienie("Dzisiaj jest do wykonania wydatek stały: " +
                        w.getNaCo() + " (" + w.getWartosc() + " zł, " +
                        formatted + ")", "Wydatek stały: " + w.getNaCo(), w.getId()));
            }
        });

        for (Przypomnienie przypomnienie : nowePrzypomnienia) {

            if (Przypomnienia.pobierzWszystkie().stream().noneMatch(p -> p.getTytul().equals(przypomnienie.getTytul()))) {
                Przypomnienia.dodaj(przypomnienie);
            }
        }

        List<String> przypomnienia = Przypomnienia.pobierzWszystkie().stream()
                .map(Object::toString).collect(Collectors.toList());
        lstPowiadomienia.setListData(przypomnienia.toArray(new String[0]));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnGotowka = new javax.swing.JButton();
        btnKontaBankowe = new javax.swing.JButton();
        btnKwotyWszystko = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDostepnaKwota = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstKwoty = new javax.swing.JList<>();
        jPanel8 = new javax.swing.JPanel();
        btnKwotaDodaj = new javax.swing.JButton();
        btnKwotaUsun = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        btnWydatkiZwykle = new javax.swing.JButton();
        btnWydatkiStale = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtSumaWydatkow = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstWydatki = new javax.swing.JList<>();
        btnWydatkiWysztko = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        btnWydatkiDodaj = new javax.swing.JButton();
        btnWydatkiUsun = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        btnPrzeliczPrognoze = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtPrognozaSumaWydatkowStalych = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPrognozaWydatkiWOstatnimMiesiacu = new javax.swing.JTextField();
        txtPrognozaWydatkiWOstatnimRoku = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtPrognozaWydatkiWTymMiesiacuRokTemu = new javax.swing.JTextField();
        txtPrognozaWMiesiacu = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtPrognozaWRoku = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstDokumentyWydatki = new javax.swing.JList<>();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstDokumenty = new javax.swing.JList<>();
        btnZapiszDokument = new javax.swing.JButton();
        btnDodajDokument = new javax.swing.JButton();
        btnUsunDokument = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        lstPowiadomienia = new javax.swing.JList<>();
        txtTytulPowiadomienia = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtPowiadomienie = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtZmienHaslo = new javax.swing.JPasswordField();
        txtZmienHasloPowtorz = new javax.swing.JPasswordField();
        jLabel17 = new javax.swing.JLabel();
        btnZmienHaslo = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        lstUzytkownicy = new javax.swing.JList<>();
        jLabel18 = new javax.swing.JLabel();
        btnWyloguj = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        txtZalogowanyJako = new javax.swing.JTextField();
        btnUsunUzytkownika = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(187, 23, 30));

        btnGotowka.setBackground(new java.awt.Color(187, 23, 30));
        btnGotowka.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnGotowka.setForeground(new java.awt.Color(255, 255, 255));
        btnGotowka.setText("Gotówka");
        btnGotowka.setBorder(null);
        btnGotowka.setBorderPainted(false);
        btnGotowka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGotowkaActionPerformed(evt);
            }
        });

        btnKontaBankowe.setBackground(new java.awt.Color(187, 23, 30));
        btnKontaBankowe.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnKontaBankowe.setForeground(new java.awt.Color(255, 255, 255));
        btnKontaBankowe.setText("Konta bankowe");
        btnKontaBankowe.setBorder(null);
        btnKontaBankowe.setBorderPainted(false);
        btnKontaBankowe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKontaBankoweActionPerformed(evt);
            }
        });

        btnKwotyWszystko.setBackground(new java.awt.Color(187, 23, 30));
        btnKwotyWszystko.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnKwotyWszystko.setForeground(new java.awt.Color(255, 255, 255));
        btnKwotyWszystko.setText("Wszystko");
        btnKwotyWszystko.setBorder(null);
        btnKwotyWszystko.setBorderPainted(false);
        btnKwotyWszystko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKwotyWszystkoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel1.setText("Podsumowanie");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel2.setText("Dostępna kwota");

        txtDostepnaKwota.setEditable(false);
        txtDostepnaKwota.setText("0 zł");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel3.setText("Lista kwot");

        lstKwoty.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(lstKwoty);

        jPanel8.setBackground(new java.awt.Color(187, 23, 30));

        btnKwotaDodaj.setBackground(new java.awt.Color(153, 153, 153));
        btnKwotaDodaj.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnKwotaDodaj.setText("Dodaj");
        btnKwotaDodaj.setBorderPainted(false);
        btnKwotaDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKwotaDodajActionPerformed(evt);
            }
        });

        btnKwotaUsun.setBackground(new java.awt.Color(153, 153, 153));
        btnKwotaUsun.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnKwotaUsun.setText("Usuń");
        btnKwotaUsun.setBorderPainted(false);
        btnKwotaUsun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKwotaUsunActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnKwotaDodaj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnKwotaUsun)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKwotaDodaj)
                    .addComponent(btnKwotaUsun))
                .addContainerGap(105, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 330, Short.MAX_VALUE))
                            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnGotowka)
                                .addGap(18, 18, 18)
                                .addComponent(btnKontaBankowe)
                                .addGap(18, 18, 18)
                                .addComponent(btnKwotyWszystko))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtDostepnaKwota)))
                        .addContainerGap())))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGotowka)
                    .addComponent(btnKontaBankowe)
                    .addComponent(btnKwotyWszystko))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDostepnaKwota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnWydatkiZwykle.setBackground(new java.awt.Color(187, 23, 30));
        btnWydatkiZwykle.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnWydatkiZwykle.setForeground(new java.awt.Color(255, 255, 255));
        btnWydatkiZwykle.setText("Wydatki zwykłe");
        btnWydatkiZwykle.setBorder(null);
        btnWydatkiZwykle.setBorderPainted(false);
        btnWydatkiZwykle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWydatkiZwykleActionPerformed(evt);
            }
        });

        btnWydatkiStale.setBackground(new java.awt.Color(187, 23, 30));
        btnWydatkiStale.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnWydatkiStale.setForeground(new java.awt.Color(255, 255, 255));
        btnWydatkiStale.setText("Wydatki stałe");
        btnWydatkiStale.setBorder(null);
        btnWydatkiStale.setBorderPainted(false);
        btnWydatkiStale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWydatkiStaleActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel4.setText("Podsumowanie");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel5.setText("Suma wydatków");

        txtSumaWydatkow.setEditable(false);
        txtSumaWydatkow.setText("0 zł");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel6.setText("Lista wydatków");

        lstWydatki.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(lstWydatki);

        btnWydatkiWysztko.setBackground(new java.awt.Color(187, 23, 30));
        btnWydatkiWysztko.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnWydatkiWysztko.setForeground(new java.awt.Color(255, 255, 255));
        btnWydatkiWysztko.setText("Wszystko");
        btnWydatkiWysztko.setBorder(null);
        btnWydatkiWysztko.setBorderPainted(false);
        btnWydatkiWysztko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWydatkiWysztkoActionPerformed(evt);
            }
        });

        jPanel9.setBackground(new java.awt.Color(187, 23, 30));

        btnWydatkiDodaj.setBackground(new java.awt.Color(153, 153, 153));
        btnWydatkiDodaj.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnWydatkiDodaj.setText("Dodaj");
        btnWydatkiDodaj.setBorderPainted(false);
        btnWydatkiDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWydatkiDodajActionPerformed(evt);
            }
        });

        btnWydatkiUsun.setBackground(new java.awt.Color(153, 153, 153));
        btnWydatkiUsun.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnWydatkiUsun.setText("Usuń");
        btnWydatkiUsun.setBorderPainted(false);
        btnWydatkiUsun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWydatkiUsunActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnWydatkiDodaj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnWydatkiUsun)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnWydatkiDodaj)
                    .addComponent(btnWydatkiUsun))
                .addContainerGap(105, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 170, Short.MAX_VALUE)
                        .addComponent(btnWydatkiStale)
                        .addGap(18, 18, 18)
                        .addComponent(btnWydatkiZwykle)
                        .addGap(18, 18, 18)
                        .addComponent(btnWydatkiWysztko)))
                .addContainerGap())
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(11, 11, 11)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(18, 18, 18)
                            .addComponent(txtSumaWydatkow, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)))
                    .addContainerGap()))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnWydatkiWysztko)
                    .addComponent(btnWydatkiStale)
                    .addComponent(btnWydatkiZwykle))
                .addGap(61, 61, 61)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(43, 43, 43)
                    .addComponent(jLabel4)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txtSumaWydatkow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(25, 25, 25)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(153, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Obszar roboczy", jPanel1);

        btnPrzeliczPrognoze.setText("Przelicz");
        btnPrzeliczPrognoze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrzeliczPrognozeActionPerformed(evt);
            }
        });

        jLabel7.setText("Suma wydatków stałych");

        txtPrognozaSumaWydatkowStalych.setEditable(false);
        txtPrognozaSumaWydatkowStalych.setText("0 zł");

        jLabel8.setText("Wydatki zwykłe w ostatnim miesiącu");

        txtPrognozaWydatkiWOstatnimMiesiacu.setEditable(false);
        txtPrognozaWydatkiWOstatnimMiesiacu.setText("0 zł");

        txtPrognozaWydatkiWOstatnimRoku.setEditable(false);
        txtPrognozaWydatkiWOstatnimRoku.setText("0 zł");

        jLabel9.setText("Wydatki zwykłe w ostatnim roku");

        jLabel10.setText("Wydatki zwykłe w tym miesiącu rok temu");

        txtPrognozaWydatkiWTymMiesiacuRokTemu.setEditable(false);
        txtPrognozaWydatkiWTymMiesiacuRokTemu.setText("0 zł");

        txtPrognozaWMiesiacu.setEditable(false);
        txtPrognozaWMiesiacu.setText("0 zł");

        jLabel11.setText("Prognozowana wartość wydatków w tym miesiącu");

        jLabel12.setText("Prognozowana wartość wydatków w tym roku");

        txtPrognozaWRoku.setEditable(false);
        txtPrognozaWRoku.setText("0 zł");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrognozaWydatkiWOstatnimMiesiacu, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPrognozaWydatkiWOstatnimRoku)
                            .addComponent(txtPrognozaSumaWydatkowStalych)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPrognozaWydatkiWTymMiesiacuRokTemu, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPrognozaWMiesiacu, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(btnPrzeliczPrognoze)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(31, 31, 31)
                        .addComponent(txtPrognozaWRoku)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPrzeliczPrognoze)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtPrognozaSumaWydatkowStalych, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtPrognozaWydatkiWOstatnimMiesiacu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtPrognozaWydatkiWOstatnimRoku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtPrognozaWydatkiWTymMiesiacuRokTemu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtPrognozaWMiesiacu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtPrognozaWRoku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(195, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Prognoza", jPanel7);

        jLabel13.setText("Wybierz wydatek");

        lstDokumentyWydatki.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstDokumentyWydatki.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstDokumentyWydatkiValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(lstDokumentyWydatki);

        jLabel14.setText("Lista dokumentów");

        lstDokumenty.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane4.setViewportView(lstDokumenty);

        btnZapiszDokument.setText("Zapisz");
        btnZapiszDokument.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZapiszDokumentActionPerformed(evt);
            }
        });

        btnDodajDokument.setText("Dodaj");
        btnDodajDokument.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajDokumentActionPerformed(evt);
            }
        });

        btnUsunDokument.setText("Usuń");
        btnUsunDokument.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsunDokumentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                    .addComponent(btnZapiszDokument, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDodajDokument, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUsunDokument, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(531, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnZapiszDokument)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDodajDokument)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUsunDokument)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Dokumenty", jPanel2);

        jLabel15.setText("Lista powiadomień");

        lstPowiadomienia.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstPowiadomienia.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstPowiadomieniaValueChanged(evt);
            }
        });
        jScrollPane5.setViewportView(lstPowiadomienia);

        txtTytulPowiadomienia.setText("Tytuł powiadomienia");

        txtPowiadomienie.setColumns(20);
        txtPowiadomienie.setRows(5);
        jScrollPane7.setViewportView(txtPowiadomienie);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTytulPowiadomienia)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtTytulPowiadomienia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 239, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Powiadomienia", jPanel3);

        jLabel16.setText("Zmień hasło");

        jLabel17.setText("Powtórz hasło");

        btnZmienHaslo.setText("Zmień hasło");
        btnZmienHaslo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZmienHasloActionPerformed(evt);
            }
        });

        lstUzytkownicy.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane6.setViewportView(lstUzytkownicy);

        jLabel18.setText("Lista użytkowników");

        btnWyloguj.setText("Wyloguj się");
        btnWyloguj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWylogujActionPerformed(evt);
            }
        });

        jLabel19.setText("Zalogowany jako");

        btnUsunUzytkownika.setText("Usuń");
        btnUsunUzytkownika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsunUzytkownikaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnUsunUzytkownika, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(txtZalogowanyJako, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 495, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnWyloguj, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel16)
                        .addComponent(txtZmienHaslo)
                        .addComponent(jLabel17)
                        .addComponent(txtZmienHasloPowtorz)
                        .addComponent(btnZmienHaslo, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnWyloguj)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtZalogowanyJako, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtZmienHaslo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtZmienHasloPowtorz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnZmienHaslo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUsunUzytkownika)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Konto użytkownika", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void aktualizujKwoty() {
        String suma;
        List<String> kwoty;
        switch (kwotaTryb) {
            case kwotaGotowka:
                suma = Kwota.sumujGotowke().toString() + " zł";
                txtDostepnaKwota.setText(suma);
                kwoty = Kwota.pobierzKwotyGotowka();
                lstKwoty.setListData(kwoty.toArray(new String[0]));
                break;
            case kwotaKonta:
                suma = Kwota.sumujPieniadzeNaKontach().toString() + " zł";
                txtDostepnaKwota.setText(suma);
                kwoty = Kwota.pobierzKwotyKonta();
                lstKwoty.setListData(kwoty.toArray(new String[0]));
                break;
            case kwotaWszystko:
                suma = Kwota.sumujWszystkieKwoty().toString() + " zł";
                txtDostepnaKwota.setText(suma);
                kwoty = Kwota.pobierzKwotyWszystkie();
                lstKwoty.setListData(kwoty.toArray(new String[0]));
                break;
        }
    }

    public void aktualizujWydatki() {
        String suma;
        List<String> wydatki;
        switch (wydatkiTryb) {
            case wydatkiZwykle:
                suma = Wydatki.sumujZwykle().toString() + " zł";
                txtSumaWydatkow.setText(suma);
                wydatki = Wydatki.pobierzWydatkiZwykle();
                lstWydatki.setListData(wydatki.toArray(new String[0]));
                break;
            case wydatkiStale:
                suma = Wydatki.sumujStale().toString() + " zł";
                txtSumaWydatkow.setText(suma);
                wydatki = Wydatki.pobierzStale();
                lstWydatki.setListData(wydatki.toArray(new String[0]));
                break;
            case wydatkiWszystkie:
                suma = Wydatki.sumujWszystkie().toString() + " zł";
                txtSumaWydatkow.setText(suma);
                wydatki = Wydatki.pobierzWszystkie();
                lstWydatki.setListData(wydatki.toArray(new String[0]));
                break;
        }

        wydatki = Wydatki.pobierzWszystkie();
        lstDokumentyWydatki.setListData(wydatki.toArray(new String[0]));
    }

    private void btnKwotyWszystkoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKwotyWszystkoActionPerformed
        kwotaTryb = kwotaWszystko;
        aktualizujKwoty();
    }//GEN-LAST:event_btnKwotyWszystkoActionPerformed

    private void btnKontaBankoweActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKontaBankoweActionPerformed
        kwotaTryb = kwotaKonta;
        aktualizujKwoty();
    }//GEN-LAST:event_btnKontaBankoweActionPerformed

    private void btnGotowkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGotowkaActionPerformed
        kwotaTryb = kwotaGotowka;
        aktualizujKwoty();
    }//GEN-LAST:event_btnGotowkaActionPerformed

    private void btnKwotaDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKwotaDodajActionPerformed
        new DodawanieKwoty(this).setVisible(true);
    }//GEN-LAST:event_btnKwotaDodajActionPerformed

    private void btnKwotaUsunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKwotaUsunActionPerformed
        String selectedValue = lstKwoty.getSelectedValue();
        if (selectedValue == null) {
            Sys.warning("Zaznaczenie", "Nie zaznaczono pozycji");
            return;
        }
        int selectedId = Integer.parseInt(selectedValue.split("]")[0].substring(1));

        Kwota.usunKwote(selectedId);
        aktualizujKwoty();
    }//GEN-LAST:event_btnKwotaUsunActionPerformed

    private void btnWylogujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWylogujActionPerformed
        Autoryzacja.wyloguj();

        Sys.info("Logowanie", "Wylogowano");

        setVisible(false);
        logowanie.setVisible(true);
    }//GEN-LAST:event_btnWylogujActionPerformed

    private void btnZmienHasloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZmienHasloActionPerformed
        String haslo = String.valueOf(txtZmienHaslo.getPassword());
        String powtorzHaslo = String.valueOf(txtZmienHasloPowtorz.getPassword());

        if (haslo.isEmpty()) {
            Sys.warning("Hasło", "Nie podano hasła");
            return;
        }

        if (powtorzHaslo.isEmpty()) {
            Sys.warning("Hasło", "Nie powtórzono hasła");
            return;
        }

        if (!haslo.equals(powtorzHaslo)) {
            Sys.warning("Hasła", "Podane hasła nie zgadzają się");
            return;
        }

        Autoryzacja.zmienHaslo(Sys.zalogowany.getId(), haslo);

        Sys.info("Hasło", "Zmieniono hasło");


    }//GEN-LAST:event_btnZmienHasloActionPerformed

    private void lstDokumentyWydatkiValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstDokumentyWydatkiValueChanged
        aktualizujDokumenty();
    }//GEN-LAST:event_lstDokumentyWydatkiValueChanged

    private void btnUsunDokumentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsunDokumentActionPerformed
        String selectedValue = lstDokumenty.getSelectedValue();
        if (selectedValue == null) {
            Sys.warning("Zaznaczenie", "Nie zaznaczono pozycji");
            return;
        }

        int selectedId = Integer.parseInt(selectedValue.split("]")[0].substring(1));

        DokumentService.usun(selectedId);

        aktualizujDokumenty();
    }//GEN-LAST:event_btnUsunDokumentActionPerformed

    private void btnDodajDokumentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajDokumentActionPerformed
        setVisible(false);
        new DodawanieDokumentu(this).setVisible(true);
    }//GEN-LAST:event_btnDodajDokumentActionPerformed

    private void btnZapiszDokumentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZapiszDokumentActionPerformed
        String selectedValue = lstDokumenty.getSelectedValue();
        if (selectedValue == null) {
            Sys.warning("Zaznaczenie", "Nie zaznaczono pozycji");
            return;
        }

        int selectedId = Integer.parseInt(selectedValue.split("]")[0].substring(1));

        Dokument dokument = DokumentService.pobierz(selectedId);

        if (dokument == null) {
            return;
        }

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Wybierz miejsce zapisania pliku");
        fileChooser.setSelectedFile(new File(dokument.getNazwaPliku()));

        int userSelection = fileChooser.showSaveDialog(this);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();

            OutputStream os;
            try {
                os = new FileOutputStream(fileToSave);
                os.write(dokument.getDane());
                os.close();

                Sys.info("Zapisywanie pliku", "Zapisano plik jako: " + fileToSave.getAbsolutePath());
            } catch (IOException e) {
                Sys.warning("Zapisywanie pliku", "Wystąpił problem z zapisem pliku");
            }
        }

    }//GEN-LAST:event_btnZapiszDokumentActionPerformed

    private void lstPowiadomieniaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstPowiadomieniaValueChanged
        String selectedValue = lstPowiadomienia.getSelectedValue();
        if (selectedValue == null) {
            return;
        }
        int selectedId = Integer.parseInt(selectedValue.split("]")[0].substring(1));

        Przypomnienie przypomnienie = Przypomnienia.pobierz(selectedId);

        txtPowiadomienie.setText(przypomnienie.getTresc());
        txtTytulPowiadomienia.setText(przypomnienie.getTytul());
    }//GEN-LAST:event_lstPowiadomieniaValueChanged

    private void btnPrzeliczPrognozeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrzeliczPrognozeActionPerformed
        Prognoza prognoza = kalkulatorwydatkow.businesslogic.Prognoza.przeliczPrognoze();

        txtPrognozaSumaWydatkowStalych.setText(prognoza.getSumaWydatkowStalych().toString());
        txtPrognozaWydatkiWOstatnimMiesiacu.setText(prognoza.getWydatkiZwykleWOstatnimMiesiacu().toString());
        txtPrognozaWydatkiWOstatnimRoku.setText(prognoza.getWydatkiZwykleWOstatnimRoku().toString());
        txtPrognozaWydatkiWTymMiesiacuRokTemu.setText(prognoza.getWydatkiZwykleWTymMiesiacuRokTemu().toString());
        txtPrognozaWMiesiacu.setText(prognoza.getPrognozowanaWartoscWydatkowWTymMiesiacu().toString());
        txtPrognozaWRoku.setText(prognoza.getPrognozowanaWartoscWydatkowWTymRoku().toString());
    }//GEN-LAST:event_btnPrzeliczPrognozeActionPerformed

    private void btnWydatkiWysztkoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWydatkiWysztkoActionPerformed
        wydatkiTryb = wydatkiWszystkie;
        aktualizujWydatki();
    }//GEN-LAST:event_btnWydatkiWysztkoActionPerformed

    private void btnWydatkiUsunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWydatkiUsunActionPerformed
        String selectedValue = lstWydatki.getSelectedValue();
        if (selectedValue == null) {
            Sys.warning("Zaznaczenie", "Nie zaznaczono pozycji");
            return;
        }
        int selectedId = Integer.parseInt(selectedValue.split("]")[0].substring(1));

        Wydatki.usunWydatek(selectedId);
        aktualizujWydatki();
    }//GEN-LAST:event_btnWydatkiUsunActionPerformed

    private void btnWydatkiDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWydatkiDodajActionPerformed
        new DodawanieWydatku(this).setVisible(true);
    }//GEN-LAST:event_btnWydatkiDodajActionPerformed

    private void btnWydatkiStaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWydatkiStaleActionPerformed
        wydatkiTryb = wydatkiStale;
        aktualizujWydatki();
    }//GEN-LAST:event_btnWydatkiStaleActionPerformed

    private void btnWydatkiZwykleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWydatkiZwykleActionPerformed
        wydatkiTryb = wydatkiZwykle;
        aktualizujWydatki();
    }//GEN-LAST:event_btnWydatkiZwykleActionPerformed

    private void btnUsunUzytkownikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsunUzytkownikaActionPerformed
        String selectedValue = lstUzytkownicy.getSelectedValue();
        if (selectedValue == null) {
            Sys.warning("Zaznaczenie", "Nie zaznaczono pozycji");
            return;
        }
        int selectedId = Integer.parseInt(selectedValue.split("]")[0].substring(1));

        if(selectedId == Sys.zalogowany.getId()) {
            Sys.warning("Usuwanie konta", "Nie można usunąć własnego konta");
            return;
        }

        Autoryzacja.usunUzytkownika(selectedId);

        aktualizujUzytkownikow();
    }//GEN-LAST:event_btnUsunUzytkownikaActionPerformed

    public void aktualizujDokumenty() {
        String selectedValue = lstDokumentyWydatki.getSelectedValue();
        if (selectedValue == null) {
            Sys.warning("Zaznaczenie", "Nie zaznaczono pozycji");
            return;
        }
        int selectedId = Integer.parseInt(selectedValue.split("]")[0].substring(1));

        List<String> dokumenty = Wydatki.pobierzDokumentyDlaWydatku(selectedId);
        lstDokumenty.setListData(dokumenty.toArray(new String[0]));
    }

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Desktop(this).setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajDokument;
    private javax.swing.JButton btnGotowka;
    private javax.swing.JButton btnKontaBankowe;
    private javax.swing.JButton btnKwotaDodaj;
    private javax.swing.JButton btnKwotaUsun;
    private javax.swing.JButton btnKwotyWszystko;
    private javax.swing.JButton btnPrzeliczPrognoze;
    private javax.swing.JButton btnUsunDokument;
    private javax.swing.JButton btnUsunUzytkownika;
    private javax.swing.JButton btnWydatkiDodaj;
    private javax.swing.JButton btnWydatkiStale;
    private javax.swing.JButton btnWydatkiUsun;
    private javax.swing.JButton btnWydatkiWysztko;
    private javax.swing.JButton btnWydatkiZwykle;
    private javax.swing.JButton btnWyloguj;
    private javax.swing.JButton btnZapiszDokument;
    private javax.swing.JButton btnZmienHaslo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JList<String> lstDokumenty;
    private javax.swing.JList<String> lstDokumentyWydatki;
    private javax.swing.JList<String> lstKwoty;
    private javax.swing.JList<String> lstPowiadomienia;
    private javax.swing.JList<String> lstUzytkownicy;
    private javax.swing.JList<String> lstWydatki;
    private javax.swing.JTextField txtDostepnaKwota;
    private javax.swing.JTextArea txtPowiadomienie;
    private javax.swing.JTextField txtPrognozaSumaWydatkowStalych;
    private javax.swing.JTextField txtPrognozaWMiesiacu;
    private javax.swing.JTextField txtPrognozaWRoku;
    private javax.swing.JTextField txtPrognozaWydatkiWOstatnimMiesiacu;
    private javax.swing.JTextField txtPrognozaWydatkiWOstatnimRoku;
    private javax.swing.JTextField txtPrognozaWydatkiWTymMiesiacuRokTemu;
    private javax.swing.JTextField txtSumaWydatkow;
    private javax.swing.JLabel txtTytulPowiadomienia;
    private javax.swing.JTextField txtZalogowanyJako;
    private javax.swing.JPasswordField txtZmienHaslo;
    private javax.swing.JPasswordField txtZmienHasloPowtorz;
    // End of variables declaration//GEN-END:variables
}
