/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kalkulatorwydatkow.gui;

import kalkulatorwydatkow.businesslogic.Wydatki;
import kalkulatorwydatkow.model.Dokument;
import kalkulatorwydatkow.model.Sys;
import kalkulatorwydatkow.service.DokumentService;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.util.List;


public class DodawanieDokumentu extends javax.swing.JFrame {

    private Desktop desktop;

    /**
     * Creates new form DodawanieDokumenty
     * @param desktop
     */
    public DodawanieDokumentu(Desktop desktop) {
        this.desktop = desktop;
        initComponents();

        init();
    }

    private void init() {
        List<String> wydatki = Wydatki.pobierzWszystkie();
        lstWydatek.setListData(wydatki.toArray(new String[0]));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstWydatek = new javax.swing.JList<>();
        fileChooser = new javax.swing.JFileChooser();
        btnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Wydatek");

        lstWydatek.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(lstWydatek);

        fileChooser.setApproveButtonText("Wybierz");
        fileChooser.setControlButtonsAreShown(false);
        fileChooser.setDialogTitle("Wybierz plik");
        fileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileChooserActionPerformed(evt);
            }
        });

        btnSave.setText("Wgraj plik i zapisz");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fileChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(fileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        File selectedFile = fileChooser.getSelectedFile();
        byte[] fileData;
        try {
            fileData = Files.readAllBytes(selectedFile.toPath());
        } catch (IOException e) {
            Sys.warning("Plik", "Nie można odczytać pliku");
            return;
        }

        String selectedValue = lstWydatek.getSelectedValue();

        if(selectedValue == null) {
            Sys.warning("Wydatek", "Zaznacz wydatek, do którego chcesz dołączyć dokument.");
            return;
        }

        int selectedWydatekId = Integer.parseInt(selectedValue.split("]")[0].substring(1));

        DokumentService.dodaj(new Dokument(fileData, selectedFile.getName(), selectedFile.getName().split("\\.")[1], selectedWydatekId));

        Sys.info("Dokument", "Dodano dokument");

        setVisible(false);
        desktop.setVisible(true);
        desktop.aktualizujDokumenty();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void fileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileChooserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileChooserActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstWydatek;
    // End of variables declaration//GEN-END:variables
}
