/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kalkulatorwydatkow.gui;

import kalkulatorwydatkow.businesslogic.Wydatki;
import kalkulatorwydatkow.model.*;

import javax.swing.*;
import java.math.BigDecimal;
import java.sql.Date;
import java.util.List;


public class DodawanieWydatku extends javax.swing.JFrame {

    ButtonGroup grp = new ButtonGroup();
    private Desktop desktop;

    /**
     * Creates new form DodawanieWydatku
     * @param desktop
     */
    public DodawanieWydatku(Desktop desktop) {
        this.desktop = desktop;
        initComponents();

        List<String> kwoty = kalkulatorwydatkow.businesslogic.Kwota.pobierzKwotyWszystkie();
        lstKwota.setListData(kwoty.toArray(new String[0]));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstKwota = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        txtWartosc = new javax.swing.JTextField();
        txtNaCo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtKomentarz = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtData = new javax.swing.JTextField();
        btnZapisz = new javax.swing.JButton();
        btnWydatekZwykly = new javax.swing.JRadioButton();
        btnWydatekStaly = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Pobrano z kwoty");

        lstKwota.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(lstKwota);

        jLabel2.setText("Wartość");

        jLabel3.setText("Na co");

        txtKomentarz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKomentarzActionPerformed(evt);
            }
        });

        jLabel4.setText("Komentarz");

        jLabel5.setText("Data (rrrr-mm-dd)");

        btnZapisz.setText("Dodaj");
        btnZapisz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZapiszActionPerformed(evt);
            }
        });

        grp.add(btnWydatekZwykly);
        btnWydatekZwykly.setSelected(true);
        btnWydatekZwykly.setText("Wydatek zwykły");

        grp.add(btnWydatekStaly);
        btnWydatekStaly.setText("Wydatek stały");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnZapisz))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))
                                    .addGap(17, 17, 17)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtWartosc)
                                        .addComponent(txtNaCo)
                                        .addComponent(txtKomentarz)
                                        .addComponent(txtData)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(btnWydatekZwykly)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnWydatekStaly)))
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtWartosc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNaCo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtKomentarz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnWydatekZwykly)
                    .addComponent(btnWydatekStaly))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnZapisz)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtKomentarzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKomentarzActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKomentarzActionPerformed

    private void btnZapiszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZapiszActionPerformed
        if (txtData.getText().isEmpty()) {
            Sys.warning("Wypełnij pole", "Wypełnij pole: data");
        }

        Date data = Date.valueOf(txtData.getText());

        String komentarz = txtKomentarz.getText();

        if (txtWartosc.getText().isEmpty()) {
            Sys.warning("Wypełnij pole", "Wypełnij pole: wartość");
        }

        BigDecimal wartosc = new BigDecimal(txtWartosc.getText());

        if (txtNaCo.getText().isEmpty()) {
            Sys.warning("Wypełnij pole", "Wypełnij pole: na co");
        }

        String naCo = txtNaCo.getText();

        String selectedValue = lstKwota.getSelectedValue();
        if (selectedValue == null) {
            Sys.warning("Zaznaczenie", "Nie zaznaczono pozycji kwoty");
            return;
        }
        int selectedId = Integer.parseInt(selectedValue.split("]")[0].substring(1));


        Wydatek wydatek;
        if (btnWydatekStaly.isSelected()) {
            wydatek = new WydatekStaly(selectedId, wartosc, naCo, komentarz, null, null, data);
        } else {
            wydatek = new WydatekZwykly(selectedId, wartosc, naCo, komentarz, null, null, data);
        }

        Wydatki.dodaj(wydatek);

        setVisible(false);
        desktop.setVisible(true);
        desktop.aktualizujWydatki();
    }//GEN-LAST:event_btnZapiszActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DodawanieWydatku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DodawanieWydatku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DodawanieWydatku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DodawanieWydatku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new DodawanieWydatku(this).setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnWydatekStaly;
    private javax.swing.JRadioButton btnWydatekZwykly;
    private javax.swing.JButton btnZapisz;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstKwota;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtKomentarz;
    private javax.swing.JTextField txtNaCo;
    private javax.swing.JTextField txtWartosc;
    // End of variables declaration//GEN-END:variables
}
