/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kalkulatorwydatkow.gui;

import kalkulatorwydatkow.businesslogic.Autoryzacja;
import kalkulatorwydatkow.model.Sys;


public class Rejestracja extends javax.swing.JFrame {

    private final Logowanie logowanie;

    /**
     * Creates new form Rejestracja
     */
    public Rejestracja(Logowanie logowanie) {
        this.logowanie = logowanie;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        txtImie = new javax.swing.JTextField();
        txtNazwisko = new javax.swing.JTextField();
        txtHaslo = new javax.swing.JPasswordField();
        txtPowtorzHaslo = new javax.swing.JPasswordField();
        btnZarejestruj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Login");

        jLabel2.setText("Hasło");

        jLabel3.setText("Powtórz hasło");

        jLabel4.setText("Imię");

        jLabel5.setText("Nazwisko");

        btnZarejestruj.setText("Zarejestruj");
        btnZarejestruj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZarejestrujActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(52, 52, 52)
                        .addComponent(txtNazwisko, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnZarejestruj))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtImie)
                            .addComponent(txtLogin)
                            .addComponent(txtHaslo)
                            .addComponent(txtPowtorzHaslo))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtHaslo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPowtorzHaslo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtImie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNazwisko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnZarejestruj)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnZarejestrujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZarejestrujActionPerformed
        String haslo = String.valueOf(txtHaslo.getPassword());
        String powtorzHaslo = String.valueOf(txtPowtorzHaslo.getPassword());
        String login = txtLogin.getText();
        String imie = txtImie.getText();
        String nazwisko = txtNazwisko.getText();

        if(haslo.isEmpty()) {
            Sys.warning("Hasło", "Nie podano hasła");
            return;
        }

        if(powtorzHaslo.isEmpty()) {
            Sys.warning("Hasło", "Nie powtórzono hasła");
            return;
        }

        if(login.isEmpty()) {
            Sys.warning("Login", "Nie podano loginu");
            return;
        }

        if(imie.isEmpty()) {
            Sys.warning("Imię", "Nie podano imienia");
            return;
        }

        if(nazwisko.isEmpty()) {
            Sys.warning("Hasło", "Nie podano nazwiska");
            return;
        }

        if(!haslo.equals(powtorzHaslo)) {
            Sys.warning("Hasła", "Podane hasła nie zgadzają się");
            return;
        }

        Autoryzacja.rejestruj(login, haslo, imie, nazwisko);

        Sys.info("Zarejestrowano", "Zarejestrowano użytkownika: " + imie + " " + nazwisko + " (" + login + ")");

        setVisible(false);
        logowanie.setVisible(true);
    }//GEN-LAST:event_btnZarejestrujActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnZarejestruj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField txtHaslo;
    private javax.swing.JTextField txtImie;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtNazwisko;
    private javax.swing.JPasswordField txtPowtorzHaslo;
    // End of variables declaration//GEN-END:variables
}
